name: Trigger Hermes Repo Action

on:
    workflow_dispatch:
    push:
        tags:
            - "v[0-9]+\\.[0-9]+\\.[0-9]+"
            - "v[0-9]+\\.[0-9]+\\.[0-9]+-rc[0-9]+"
jobs:
    trigger:
        runs-on: ubuntu-latest

        steps:
            -   name: Trigger  Other Repo Workflow
                run: |
                    curl -X POST \
                    -u ${{ secrets.INFORMAL_BOT_TOKEN }} \
                    -H "Accept: application/vnd.github.everest-preview+json" \
                    "https://api.github.com/repos/informalsystems/hermes/dispatches" \
                    -d '{
                    "event_type": "trigger-workflow",
                    "client_payload": {
                         "gaiad_version": "${{ github.sha }}",
                         "hermes_version": "v1.6.0"
                        }
                    }'

            -   name: Wait for hermes repo workflow
                run: |
                    sudo apt-get install jq
                    TOKEN="${{ secrets.INFORMAL_BOT_TOKEN }}" 
                    WORKFLOW_NAME="tested_by_gaia.yml"
                    
                    while : ; do
                      WORKFLOW_RUN=$(curl -s -H "Authorization: token $TOKEN" \
                        "https://api.github.com/repos/informalsystems/hermes/actions/workflows/$WORKFLOW_NAME/runs" \
                        | jq '.workflow_runs[0]')
                    
                      STATUS=$(echo $WORKFLOW_RUN | jq -r '.status')
                      CONCLUSION=$(echo $WORKFLOW_RUN | jq -r '.conclusion')

                      echo "Workflow status: $STATUS"

                      if [ "$STATUS" == "completed" ]; then
                        break
                      fi
                    
                      sleep 60 # Wait for a minute before checking again
                    done
                    
                    if [ "$CONCLUSION" != "success" ]; then
                      echo "Other workflow failed with conclusion: $CONCLUSION"
                      exit 1
                    fi






